tasks:
  HTML:
    dictionary:
      wordlists:
        - config/wordlist.txt
    sources:
      - "./build/**/*.html"
    pipeline:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
            - :matches(code, pre)
            - script
            - style
    aspell:
      lang: en
      mode: html
